lib-test.exe: lib-test.o intrinsic.o
	gcc -Wall lib-test.o intrinsic.o -o lib-test.exe

lib-test.o: lib-test.c
	gcc -Wall -c lib-test.c -o lib-test.o

intrinsic.o: intrinsic.c
	gcc -Wall -c intrinsic.c -o intrinsic.o